site_name: Python-Markdown
site_url: https://Python-Markdown.github.io/
repo_url: https://github.com/Python-Markdown/markdown
repo_name: Python-Markdown/markdown
site_author: "The Python-Markdown Project"
copyright: "Copyright &copy; 2010-2026 The Python-Markdown Project"

use_directory_urls: true
watch: [markdown, scripts, docs/templates]

theme:
  variant: modern
  logo: py.png
  favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - navigation.top
    # - content.action.edit
    # - content.action.view
    - content.code.copy
    - content.tooltips
    - content.footnote.tooltips
    - search.highlight
    
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode


    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: lucide/sun
        name: Switch to dark mode
      primary: green
      accent:  light green

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: lucide/moon
        name: Switch to system preference
      primary: green
      accent:  light green

extra_css:
  - mkdocstrings.css

nav:
  - Home: index.md
  - Usage:
    - Installation: install.md
    - Library Reference: library.md
    - Command Line: cli.md
    - Sanitization and Security: sanitization.md
    - Extensions: 
      - extensions/index.md
      - Abbreviations: extensions/abbreviations.md
      - Admonition: extensions/admonition.md
      - Attribute Lists: extensions/attr_list.md
      - CodeHilite: extensions/code_hilite.md
      - Definition Lists: extensions/definition_lists.md
      - Extra: extensions/extra.md
      - Fenced Code Blocks: extensions/fenced_code_blocks.md
      - Footnotes: extensions/footnotes.md
      - Legacy Attributes: extensions/legacy_attrs.md
      - Legacy Emphasis: extensions/legacy_em.md
      - Meta-Data: extensions/meta_data.md
      - New Line to Break: extensions/nl2br.md
      - Markdown in HTML: extensions/md_in_html.md
      - Sane Lists: extensions/sane_lists.md
      - SmartyPants: extensions/smarty.md
      - Table of Contents: extensions/toc.md
      - Tables: extensions/tables.md
      - WikiLinks: extensions/wikilinks.md
  - Development:
    - Extension API: extensions/api.md
    - Test Tools: test_tools.md
    - API Reference:
      - <code>markdown</code>: reference/markdown.md
      - <code>markdown.&#8203;preprocessors</code>: reference/markdown.preprocessors.md
      - <code>markdown.&#8203;blockparser</code>: reference/markdown.blockparser.md
      - <code>markdown.&#8203;blockprocessors</code>: reference/markdown.blockprocessors.md
      - <code>markdown.&#8203;treeprocessors</code>: reference/markdown.treeprocessors.md
      - <code>markdown.&#8203;inlinepatterns</code>: reference/markdown.inlinepatterns.md
      - <code>markdown.&#8203;postprocessors</code>: reference/markdown.postprocessors.md
      - <code>markdown.&#8203;serializers</code>: reference/markdown.serializers.md
      - <code>markdown.&#8203;util</code>: reference/markdown.util.md
      - <code>markdown.&#8203;htmlparser</code>: reference/markdown.htmlparser.md
      - <code>markdown.&#8203;test_tools</code>: reference/markdown.test_tools.md
      - <code>markdown.&#8203;extensions</code>: reference/markdown.extensions.md
      - <code>markdown.&#8203;extensions.&#8203;abbr</code>: reference/markdown.extensions.abbr.md
      - <code>markdown.&#8203;extensions.&#8203;admonition</code>: reference/markdown.extensions.admonition.md
      - <code>markdown.&#8203;extensions.&#8203;attr_list</code>: reference/markdown.extensions.attr_list.md
      - <code>markdown.&#8203;extensions.&#8203;codehilite</code>: reference/markdown.extensions.codehilite.md
      - <code>markdown.&#8203;extensions.&#8203;def_list</code>: reference/markdown.extensions.def_list.md
      - <code>markdown.&#8203;extensions.&#8203;extra</code>: reference/markdown.extensions.extra.md
      - <code>markdown.&#8203;extensions.&#8203;fenced_code</code>: reference/markdown.extensions.fenced_code.md
      - <code>markdown.&#8203;extensions.&#8203;footnotes</code>: reference/markdown.extensions.footnotes.md
      - <code>markdown.&#8203;extensions.&#8203;legacy_attrs</code>: reference/markdown.extensions.legacy_attrs.md
      - <code>markdown.&#8203;extensions.&#8203;legacy_em</code>: reference/markdown.extensions.legacy_em.md
      - <code>markdown.&#8203;extensions.&#8203;md_in_html</code>: reference/markdown.extensions.md_in_html.md
      - <code>markdown.&#8203;extensions.&#8203;meta</code>: reference/markdown.extensions.meta.md
      - <code>markdown.&#8203;extensions.&#8203;nl2br</code>: reference/markdown.extensions.nl2br.md
      - <code>markdown.&#8203;extensions.&#8203;sane_lists</code>: reference/markdown.extensions.sane_lists.md
      - <code>markdown.&#8203;extensions.&#8203;smarty</code>: reference/markdown.extensions.smarty.md
      - <code>markdown.&#8203;extensions.&#8203;tables</code>: reference/markdown.extensions.tables.md
      - <code>markdown.&#8203;extensions.&#8203;toc</code>: reference/markdown.extensions.toc.md
      - <code>markdown.&#8203;extensions.&#8203;wikilinks</code>: reference/markdown.extensions.wikilinks.md
  - About:
    - Contributing to Python-Markdown: contributing.md
    - Changelog: changelog.md
    - Authors: authors.md

validation:
  invalid_links: true
  invalid_link_anchors: true
  unresolved_references: false
  unresolved_footnotes: true
  unused_definitions: true
  unused_footnotes: true
  shadowed_definitions: true
  shadowed_footnotes: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - smarty
  - toc:
      permalink: "§"
  - mdx_gh_links:
      user: Python-Markdown
      repo: markdown
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
- search
- mkdocstrings:
    custom_templates: docs/templates
    handlers:
      python:
        inventories:
        - https://docs.python.org/3/objects.inv
        options:
          annotations_path: brief
          docstring_options:
            ignore_init_summary: true
          docstring_style: google
          docstring_section_style: list
          extensions:
          - scripts/griffe_extensions.py:DeprecatedExtension
          - scripts/griffe_extensions.py:PriorityTableExtension:
              paths:
                - markdown.preprocessors.build_preprocessors
                - markdown.blockprocessors.build_block_parser
                - markdown.treeprocessors.build_treeprocessors
                - markdown.inlinepatterns.build_inlinepatterns
                - markdown.postprocessors.build_postprocessors
          filters: ["!^_"]
          group_by_category: false
          heading_level: 1
          inherited_members: true
          members_order: source
          merge_init_into_class: true
          separate_signature: false
          show_root_heading: true
          show_object_full_path: true
          show_signature_annotations: true
          show_source: false
          show_symbol_type_heading: true
          show_symbol_type_toc: false
          signature_crossrefs: false
          summary: true
          extra:
            source:
              repo: https://github.com/Python-Markdown/markdown
              tag: !!python/name:markdown.__version__
              title: "View source code on GitHub."
