#!/bin/bash
test_dirs=( "markdowntest-cases" "php-markdown-cases" "php-markdown-extra-cases" "tm-cases" )

old_ext="text"
new_ext="txt"

for (( i = 0 ; i < "${#test_dirs[@]}"; i++ ))
do
    for j in "${test_dirs[$i]}"/*.${old_ext} 
    do 
        mv "$j" "${j/.text}".${new_ext} 
    done
done


